//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File Name : trip.cs
// Auto-generated and String dayString and IEnumerable<SelectListItem> timeList properties were added
//
// Author : Sam Sangkyun Park
// Date Created : Oct. 11, 2015
// Revision History : Version 1 created : Oct. 11, 2015

namespace SPBusService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using SPBusService.Models;
    
    public partial class trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trip()
        {
            this.tripStops = new HashSet<tripStop>();
        }
    
        [ScaffoldColumn(false)]
        public int tripId { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Start Time")]
        public int routeScheduleId { get; set; }

        //Avaiable for EditorForModel()
        [Required]
        [Display(Name="Trip Date")]
        public System.DateTime tripDate { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Driver")]
        public int driverId { get; set; }

        [Required]
        [ScaffoldColumn(false)]
        [Display(Name = "Bus #")]
        public int busId { get; set; }

        //Avaiable for EditorForModel()
        [DataType(DataType.MultilineText)]
        public string comments { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual driver driver { get; set; }
        public virtual routeSchedule routeSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tripStop> tripStops { get; set; }

        [ScaffoldColumn(false)]

        //For SPBusService.Views.SPTrip.Create view-model
        public virtual string dayString { get; set; }

        //For SPBusService.Views.SPTrip.Create view-model
        //Type of this model should be SPBusService.Model.StartTime model
        public virtual IEnumerable<SelectListItem> timeList { get; set; }

    }
}
